In [1]:
# define tokenized sentences as training data
tokenized_sentences=[['Hello','This','is','python','training','by','Rajavardhan'],
                    ['Hello','This','is','Java','training','by','Rajavardhan'],
                    ['Hello','This','is','Data Science','training','by','Rajavardhan'],
                    ['Hello','This','is','Ml','training','by','Rajavardhan']]

In [2]:
# Training word2Vec Model
from gensim.models import Word2Vec
import warnings
warnings.filterwarnings('ignore')
mymodel=Word2Vec(tokenized_sentences,min_count=1)# min_count =1 means consider all the words if it occurs one time also

C:\Users\Rajavardhan\Anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [3]:
# Summarizing the loaded model
print(mymodel)

Word2Vec(vocab=10, vector_size=100, alpha=0.025)


In [4]:
# Summarize vocabulary
words=list(mymodel.wv.index_to_key)

In [5]:
print(words)

['Rajavardhan', 'by', 'training', 'is', 'This', 'Hello', 'Ml', 'Data Science', 'Java', 'python']


In [6]:
# finding most similar words for word 'Data'
mymodel.wv.most_similar('Data Science')


[('Rajavardhan', 0.09291724115610123),
 ('Ml', 0.004842519294470549),
 ('training', -0.00275400816462934),
 ('is', -0.013679755851626396),
 ('This', -0.028490997850894928),
 ('Hello', -0.05774582922458649),
 ('python', -0.09326909482479095),
 ('by', -0.11555546522140503),
 ('Java', -0.14454567432403564)]

In [7]:
# mymodel.wv.most_similar('life Science') 
# we can't find the similar words for unrealted words, this is limitation of the moethod

### Option 2: Creating Embedding model using Keras

In [8]:
import numpy as np
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [9]:
# Defining the documents
sent=['Hello,how are you',
     'how are you',
     'how are you doing',
     'I am doing great',
     'I am doing good',
     'I am good']

In [10]:
# defining class labels
sent_labels=array([1,1,1,0,0,0])

In [11]:
# integer encoding of the documents
my_vocab_size=30
encoded_sent=[one_hot(i,my_vocab_size)for i in sent]
print(encoded_sent)

[[8, 2, 26, 6], [2, 26, 6], [2, 26, 6, 13], [26, 11, 13, 13], [26, 11, 13, 5], [26, 11, 5]]


In [12]:
# padding documents to a max length=5
length=5
padded_sent=pad_sequences(encoded_sent,maxlen=length,padding='pre')
print(padded_sent)

[[ 0  8  2 26  6]
 [ 0  0  2 26  6]
 [ 0  2 26  6 13]
 [ 0 26 11 13 13]
 [ 0 26 11 13  5]
 [ 0  0 26 11  5]]


In [13]:
# defining the model
mymodel=Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(1,activation='sigmoid'))

In [14]:
# complining the model
mymodel.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
# fitting the model
mymodel.fit(padded_sent,sent_labels,epochs=30)

Epoch 1/30
1/1 [==============================] - 27s 27s/step - loss: 0.6998 - accuracy: 0.3333
Epoch 2/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6978 - accuracy: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6959 - accuracy: 0.5000
Epoch 4/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6940 - accuracy: 0.5000
Epoch 5/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6921 - accuracy: 0.3333
Epoch 6/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6902 - accuracy: 0.5000
Epoch 7/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6883 - accuracy: 0.8333
Epoch 8/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6864 - accuracy: 0.8333
Epoch 9/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6844 - accuracy: 0.8333
Epoch 10/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6825 - accuracy: 0.8333
Epoch 11/30
1/1 [=====================

In [19]:
# Evaluate the model
modelloss,modelaccuracy=mymodel.evaluate(padded_sent,sent_labels,verbose=0)
print('Accuracy: %f'%(modelaccuracy*100))

Accuracy: 100.000000


### Prediction part

In [20]:
mysent_to_predict =['how are you Swathi',
                   'T am good']

In [22]:
# integer encoding of the documents
vocab_size=30
encoded=[one_hot(d,vocab_size)for d in mysent_to_predict]
print(encoded)

[[2, 26, 6, 2], [17, 11, 5]]


In [23]:
# padding the documents to a maximum length of 5 words
max_length=5
mypadded=pad_sequences(encoded, maxlen=length,padding='pre')
print(mypadded)

[[ 0  2 26  6  2]
 [ 0  0 17 11  5]]


In [25]:
mymodel.predict_classes(mypadded)

array([[1],
       [0]])